export const adminConstants = {
  ADD_CONTENT_ROW: 'ADD_REWARD',
  GET_ALL_CONTENT: 'GET_ALL_CONTENT',
  GET_ALL_REWARDS: 'GET_ALL_REWARDS',
  DELETE_CONTENT_ROW: 'DELETE_CONTENT_ROW',
  EDIT_CONTENT_ROW: 'EDIT_CONTENT_ROW',
  DELETE_CONTENT_ROW_SUCCESS: 'DELETE_CONTENT_ROW_SUCCESS',
  LIMIT: 7,
};
