export const userConstants = {
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  RESET_ERRORS: 'RESET_ERRORS',
};
